[package]
name = "kano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano-win = "0.30.0"
vulkano = "0.30.0"
colored = "2.0.0"
